name: MYCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          node -v
          npm -v
          pwd
          npm install
          npm run build
          rm -rf /home/yang/action-runner/html
          mv build /home/yang/action-runner/html

