name: MYCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
        env:
          NGINX_PORT: 80

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          node -v
          echo secrect ${{ secrets.MYSECRET }}
          curl localhost:8080
